### ISSUE TITLE
Electron driver intermittent issues

### ISSUE THREAD

**Issue by jleeh** [robertgates55/frameworkium-core#25]
Note: Issue is for tracking and visibility in-case this is discovered by someone else during my investigation/fix.

When running Electron driver remotely with 'gridURL' defined, tests are executed properly, and correctly, until randomly one test will report an error, then subsequently after that the rest of the tests fail.

First error:
> 13:42:23.451 [main] ERROR com.frameworkium.listeners.ScreenshotListener - Unable to take screenshot - org.openqa.selenium.remote.SessionNotFoundException: Session ID is null. Using WebDriver after calling quit()?

Subsequent errors after that:
> 13:43:36.115 [main] ERROR com.frameworkium.listeners.ScreenshotListener - Unable to take screenshot - org.openqa.selenium.WebDriverException: unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html

Due to tests working properly before this, It's quite baffling. Looking into it.

**Comment by Mjl33** [comment]
I have been investigating this on and off, but manage to have a serious look into this today.

This is not related to Electron driver specifically. I have been seeing this on and off. 

I manage to reproduce this by having @Visible fail on purpose (Just put in an erroneous css)
It only fails on the grid only and causes all subsequent test to SKIP because of screenshotlistener error

I believe its a race condition between TestListener setting test as a fail when BasePage: waitForObjectToBeVisible line145 timesout 
AND
BaseTest: configureDriverBasedOnParams() resetting browser at a inopportune time when a call by the ScreenshotListener is made while the browser is being reset

I don't have full understanding of it yet, as it it hard to debug on the grid.
I might try to find a way to get listeners to log the events and watch for race conditions

**Comment by jleeh** [comment]
Hey MJ,

I should of updated this issue as I found out the issue with the help of our senior front-end dev. Basically, native electron applications don't allow the support of native chromium plugins. Chromedriver injects a basic screenshot plugin into Chrome on start-up, but when electron is used, it can't do that as the plugin API isn't supported.

I've been working on the code to basically add logic to see whether screenshots are supported in the browser (just electron which isn't ATM), and I'll hopefully be raising a pull request for that today.

**Comment by jleeh** [comment]
Closing this issue due to the opening of the pull request which circumvents these issues.
